<?php

namespace frontend\controllers;

use backend\models\About;
use backend\models\Acceptance;
use backend\models\Contact;
use backend\models\Course;
use backend\models\Departments;
use backend\models\Districts;
use backend\models\Documents;
use backend\models\DocumentsItem;
use backend\models\Faculty;
use backend\models\Img;
use backend\models\Leader;
use backend\models\Leadercategory;
use backend\models\Page;
use backend\models\Post;
use backend\models\Postcategory;
use backend\models\Quarters;
use backend\models\Video;
use backend\models\Virtual;
use backend\modules\menumanager\models\Menu;
use common\models\News;
use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\BaseObject;
use yii\base\InvalidArgumentException;
use yii\data\ActiveDataProvider;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

/**
 * Site controller
 */
class SiteController extends Controller
{
    public function init()
    {
        $til = Yii::$app->session->get('til', 'uz');
        if ($til != 'ru' && $til != 'en') {
            $til = 'uz';
        }
        Yii::$app->language = $til;
        parent::init();
    }

    /**
     * {@inheritdoc}
     */
    public $layout = "shablon";

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $news = Post::find()->where(['status' => 1])->orderBy('date DESC')->limit(3)->all();
        $images = Img::find()->where(['status' => 1])->orderBy('id DESC')->limit(3)->asArray()->all();
        $video = Video::find()->where(['status' => 1])->orderBy('id DESC')->limit(3)->asArray()->all();
        return $this->render('index', ['images' => $images, 'videos' => $video, 'news' => $news,]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $username = Yii::$app->request->post('username');
        $password = Yii::$app->request->post('password');
        $model = new LoginForm();
        $model->username = $username;
        $model->password = $password;
        if ($model->login()) {
            Yii::$app->session->setFlash("success", "Muvaffaqiyatli amalga oshirildi");
            return $this->goBack();
        } else {
            Yii::$app->session->setFlash("error", "Xatolik yuz berdi");
            $model->password = '';
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        $id = Yii::$app->request->get("id");
        $news = About::find()->where(['slug' => $id])->asArray()->one();
        $menus = Menu::find()->where(['id' => 71])->one();
        return $this->render('about', ['news' => $news, 'menus' => $menus]);

    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $username = Yii::$app->request->post('username');
        $password = Yii::$app->request->post('password');
        $email = Yii::$app->request->post('email');
        $model = new SignupForm();
        $model->username = $username;
        $model->password = $password;
        $model->email = $email;
        if ($model->signup()) {
            Yii::$app->session->setFlash('success', "siz ro'yxatdan o'tingiz tizimga kirish uchun login parolingizni tering");
            return $this->redirect(['/site/login']);
        }
        Yii::$app->session->setFlash('error', 'xatolik yuz berdi username passwor yoki email xato kiritildi ');
        return $this->render('login',
            [
                'model' => $model,
            ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @return yii\web\Response
     * @throws BadRequestHttpException
     */
    public function actionVerifyEmail($token)
    {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($user = $model->verifyEmail()) {
            if (Yii::$app->user->login($user)) {
                Yii::$app->session->setFlash('success', 'Your email has been confirmed!');
                return $this->goHome();
            }
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    /**
     * Resend verification email
     *
     * @return mixed
     */
    public function actionResendVerificationEmail()
    {
        $model = new ResendVerificationEmailForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            }
            Yii::$app->session->setFlash('error', 'Sorry, we are unable to resend verification email for the provided email address.');
        }

        return $this->render('resendVerificationEmail', [
            'model' => $model
        ]);
    }

    public function actionChange($til)
    {
        Yii::$app->session->set('til', $til);
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionContactForm()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                if ($model->subject != Null) {
                    $contactModel = new Contact([
                        'scenario' => 'contact-form',
                        'name' => $model->name,
                        'email' => $model->email,
                        'subject' => $model->subject,
                        'message' => $model->message,
                        'phone' => $model->phone,
                    ]);
                } else {
                    $contactModel = new Contact([
                        'scenario' => 'contact-form',
                        'name' => $model->name,
                        'email' => $model->email,
                        'message' => $model->message,
                        'phone' => $model->phone,
                    ]);
                }
                if ($contactModel->save()) {
                    Yii::$app->session->setFlash('success', 'Arizangiz qabul qilindi');
                    return $this->redirect(['site/index']);
                }
            } else {
                Yii::$app->session->setFlash('error', 'Xatolik yuz berdi!');
            }
        }
        return $this->render('contact-form', ['model' => $model]);
    }

    public function actionDocuments()
    {
        $id = Yii::$app->request->get('id');
        $menu_id = Yii::$app->request->get('menu_id');
        $menus = Menu::find()->where(['id' => $menu_id])->one();
        $document = Documents::find()->where(['status' => 1, 'slug' => $id])->asArray()->one();
        $documents_items = DocumentsItem::find()->where(['status' => 1, 'document_id' => $document['id']])->asArray()->all();
        return $this->render('documents', ['documents_items' => $documents_items, 'menus' => $menus]);
    }

    public function actionPage()
    {
        $id = Yii::$app->request->get('id');
        $menu_id = Yii::$app->request->get('menu_id');
        if ($id && $menu_id != Null) {
            $menus = Menu::find()->where(['id' => $menu_id])->one();
            $page = Page::find()->where(['slug' => $id])->asArray()->one();
            $leader_category = Leadercategory::find()->andWhere(['slug' => $id])->one();
            if (isset($leader_category)) {
                $leaders = Leader::find()->andWhere(['category_id' => $leader_category->id])->all();
            }
            return $this->render('page', ['page' => $page, 'menus' => $menus,'leaders'=>$leaders]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

    }

    public function actionFakultet()
    {
        $id = Yii::$app->request->get('id');
        $menu_id = Yii::$app->request->get('menu_id');
        if ($id && $menu_id != Null) {
            $menus = Menu::find()->where(['id' => $menu_id])->one();
            $faculty = Faculty::find()->where(['slug' => $id])->asArray()->one();
            $leader_category = Leadercategory::find()->andWhere(['slug' => $id])->one();
            if (isset($leader_category)) {
                $leaders = Leader::find()->andWhere(['category_id' => $leader_category->id])->all();
            }
            return $this->render('faculty', ['faculty' => $faculty, 'menus' => $menus, 'leaders' => $leaders]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

    }

    public function actionKafedra()
    {
        $id = Yii::$app->request->get('id');
        $menu_id = Yii::$app->request->get('menu_id');
        if ($id && $menu_id != Null) {
            $menus = Menu::find()->where(['id' => $menu_id])->one();
            $faculty = Departments::find()->where(['slug' => $id])->asArray()->one();
            $leader_category = Leadercategory::find()->andWhere(['slug' => $id])->one();
            if (isset($leader_category)) {
                $leaders = Leader::find()->andWhere(['category_id' => $leader_category->id])->all();
            }
            return $this->render('departments', ['departments' => $faculty, 'menus' => $menus, 'leaders' => $leaders]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

    }

    public function actionRahbariyat()
    {
        $id = Yii::$app->request->get('id');
        $menu_id = Yii::$app->request->get('menu_id');
        if ($id && $menu_id != Null) {
            $menus = Menu::find()->where(['id' => $menu_id])->one();
            $leadercategory = Leadercategory::find()->where(['slug' => $id])->asArray()->one();
            $leader = Leader::find()->where(['status' => 1, 'category_id' => $leadercategory['id']])->all();

            return $this->render('leader', ['leaders' => $leader, 'menus' => $menus, 'category' => $leadercategory]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

    }

    public function actionGallery()
    {
        $images = Img::find()->where(['status' => 1])->orderBy('id DESC')->asArray();
        $provider = new ActiveDataProvider([
            'query' => $images,
            'pagination' => [
                'pageSize' => 12
            ]
        ]);
        return $this->render("gallery", ['provider' => $provider]);
    }

    public function actionVideo()
    {
        $video = Video::find()->where(['status' => 1])->orderBy('id DESC')->asArray();
        $provider = new ActiveDataProvider([
            'query' => $video,
            'pagination' => [
                'pageSize' => 9
            ]
        ]);
        return $this->render('video', ['provider' => $provider]);
    }

    public function actionNews()
    {
        $id = Yii::$app->request->get('id');
        $category = Postcategory::find()->where(['slug' => $id])->asArray()->one();
        $news = Post::find()->where(['status' => 1, 'category_id' => $category['id']])->orderBy('date DESC')->asArray();
        $provider = new ActiveDataProvider(
            [
                'query' => $news,
                'pagination' => [
                    'pageSize' => 9,
                ]
            ]
        );
        return $this->render('news', ['provider' => $provider, 'category' => $category]);
    }

    public function actionVirtualReception()
    {
        $model = new Virtual();
        if ($model->load(Yii::$app->request->post())) {
            $model->file = UploadedFile::getInstance($model, 'file');
            if ($model->file) {
                $model->file->saveAs('uploads/virtual/' . $model->file->baseName . '.' . $model->file->extension);
            }
            $model->address = Yii::$app->request->post('manzil');
            $model->fog = Yii::$app->request->post('tuman');
            $model->province = Yii::$app->request->post('viloyat');
            $model->gender = Yii::$app->request->post('gender');
            $model->faculty_id = Yii::$app->request->post('fakultet');
            $model->status = 0;
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Arizangiz qabul qilindi');
                return $this->redirect(['site/index']);
            } else {
                Yii::$app->session->setFlash('error', 'xatolik yuz berdi');
            }
            return $this->redirect(Yii::$app->request->referrer);
        }
        return $this->render('virtual-reception', ['model' => $model]);
    }

    public function actionQabul()
    {
        $model = new Acceptance();
        if ($model->load(Yii::$app->request->post())) {
            $model->quater_id = Yii::$app->request->post('manzil');
            $model->region_id = Yii::$app->request->post('viloyat');
            $model->district_id = Yii::$app->request->post('tuman');
            $model->category_id = Yii::$app->request->post('rahbar');
            $model->status = 1;
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Arizangiz qabul qilindi');
                return $this->redirect(['site/index']);
            } else {
                Yii::$app->session->setFlash('error', 'xatolik yuz berdi');
            }
        }
        return $this->render('qabul', ['model' => $model]);
    }

    public function actionDisrtict()
    {
        $id = Yii::$app->request->queryParams['id'];
        $district = Districts::find()->where(['region_id' => $id])->all();
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return ['districts' => $district,];
    }

    public function actionAddress()
    {
        $id = Yii::$app->request->queryParams['id'];
        $address = Quarters::find()->where(['district_id' => $id])->all();
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return ['address' => $address];
    }

    public function actionDetail()
    {
        $title = Yii::t("app", "News");
        $id = Yii::$app->request->get('id');
        $menu_id = Yii::$app->request->get('menu_id');
        if ($id && $menu_id != Null) {

            $menus = Menu::find()->where(['id' => $menu_id])->one();

            $news = Post::find()->where(['status' => 1, 'slug' => $id])->one();
            $news->updateCounters(['seen' => 1]);
            return $this->render('detail', [
                'news' => $news,
                'menus' => $menus,
                'title' => $title
            ]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionAll()
    {

        $news = Post::find()->where(['status' => 1])->orderBy('id DESc');
        $provider = new ActiveDataProvider([
            'query' => $news,
            'pagination' => [
                'pageSize' => 9
            ]
        ]);
        return $this->render('all', ['provider' => $provider]);
    }

    public function actionSearch()
    {
        $this->enableCsrfValidation = false;
        $search = Yii::$app->request->get('search');
        $news = Post::find()->where(['status' => 1])->andwhere(['like', 'title_uz', $search])->orWhere(['like', 'title_ru', $search])->orWhere(['like', 'title_en', $search]);
        $provider = new ActiveDataProvider([
            'query' => $news,
            'pagination' => [
                'pageSize' => 3,
            ],
        ]);
        $result2 = Page::find()->where(['status' => 1])->andwhere(['like', 'title_uz', $search])->orWhere(['like', 'title_ru', $search])->orWhere(['like', 'title_en', $search])->all();
        return $this->render("search", ['provider' => $provider, 'search2' => $result2]);
    }

    public function actionSitemap()
    {
        $menus = Menu::find()->where(['id' => 71])->one();
        $category = Menu::find()->where(['lvl' => 1])->all();
        $menu = Menu::find()->where(['lvl' => 2])->all();
        return $this->render("sitemap", ['category' => $category, 'menu' => $menu, 'menuss' => $menus]);
    }

    public function actionFullGallery()
    {
        $menus = Menu::find()->where(['id' => 71])->one();
        $slug = Yii::$app->request->get('id');
        $fullgallery = Img::find()->where(['slug' => $slug])->asArray()->one();
        return $this->render('full-gallery', ['fullgallery' => $fullgallery, 'menus' => $menus]);
    }

    public function actionSchedule()
    {
        $categories = Course::find()->where(['status' => 1])
            ->all();
        return $this->render('schedule', ['categories' => $categories]);
    }
}
